require 'faker'

20.times do 
  Customer.create(customer_name: Faker::Company.name)
end


# PickOneGroup.create!([
#   {model_id: 1, description: "Pick paper deck for c14000"},
#   {model_id: 1, description: "Pick one output assembly for C12000/C14000"},
#   {model_id: 1, description: "Pick a print controller for the C12000/C14000:"}
# ])
# ModelAssembly.create!([
#   {model_id: 1, assembly_id: 15, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 16, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 17, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 22, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 24, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 25, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 26, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 27, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 29, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 30, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 31, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 32, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 38, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 39, required: nil, pick_one_group_id: nil},
#   {model_id: 2, assembly_id: 12, required: nil, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 2, required: true, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 42, required: true, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 43, required: false, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 44, required: false, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 45, required: true, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 46, required: true, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 12, required: nil, pick_one_group_id: 1},
#   {model_id: 1, assembly_id: 13, required: nil, pick_one_group_id: 1},
#   {model_id: 1, assembly_id: 14, required: nil, pick_one_group_id: 1},
#   {model_id: 1, assembly_id: 20, required: nil, pick_one_group_id: 2},
#   {model_id: 1, assembly_id: 21, required: nil, pick_one_group_id: 2},
#   {model_id: 1, assembly_id: 18, required: true, pick_one_group_id: nil},
#   {model_id: 1, assembly_id: 33, required: nil, pick_one_group_id: 3},
#   {model_id: 1, assembly_id: 34, required: nil, pick_one_group_id: 3},
#   {model_id: 1, assembly_id: 35, required: nil, pick_one_group_id: 3},
#   {model_id: 1, assembly_id: 36, required: nil, pick_one_group_id: 3},
#   {model_id: 1, assembly_id: 19, required: true, pick_one_group_id: nil}
# ])
# Model.create!([
#   {name: "c12000", short_description: "new Cypress model for high speed production"},
#   {name: "c14000", short_description: "140 page per minute Cypress model"}
# ])
# ItemsAssembly.create!([
#   {item_id: 3, assembly_id: 42, required: true},
#   {item_id: 4, assembly_id: 42, required: true},
#   {item_id: 132, assembly_id: 47, required: true},
#   {item_id: 1, assembly_id: 47, required: true},
#   {item_id: 1, assembly_id: 46, required: true},
#   {item_id: 1, assembly_id: 2, required: nil},
#   {item_id: 7, assembly_id: 43, required: false},
#   {item_id: 8, assembly_id: 43, required: false},
#   {item_id: 9, assembly_id: 43, required: false},
#   {item_id: 10, assembly_id: 43, required: false},
#   {item_id: 65, assembly_id: 31, required: false},
#   {item_id: 5, assembly_id: 44, required: false},
#   {item_id: 6, assembly_id: 44, required: false},
#   {item_id: 99, assembly_id: 45, required: true},
#   {item_id: 64, assembly_id: 31, required: false},
#   {item_id: 53, assembly_id: 31, required: false},
#   {item_id: 66, assembly_id: 31, required: false},
#   {item_id: 67, assembly_id: 31, required: false},
#   {item_id: 68, assembly_id: 31, required: false},
#   {item_id: 69, assembly_id: 31, required: false},
#   {item_id: 70, assembly_id: 31, required: false},
#   {item_id: 71, assembly_id: 31, required: false},
#   {item_id: 72, assembly_id: 31, required: false},
#   {item_id: 73, assembly_id: 31, required: false},
#   {item_id: 74, assembly_id: 31, required: false},
#   {item_id: 75, assembly_id: 31, required: false},
#   {item_id: 76, assembly_id: 31, required: false},
#   {item_id: 77, assembly_id: 31, required: false},
#   {item_id: 78, assembly_id: 31, required: false},
#   {item_id: 1, assembly_id: 1, required: true},
#   {item_id: 99, assembly_id: 1, required: false},
#   {item_id: 3, assembly_id: 1, required: true},
#   {item_id: 4, assembly_id: 1, required: true},
#   {item_id: 5, assembly_id: 1, required: false},
#   {item_id: 6, assembly_id: 1, required: false},
#   {item_id: 7, assembly_id: 1, required: false},
#   {item_id: 8, assembly_id: 1, required: false},
#   {item_id: 9, assembly_id: 1, required: false},
#   {item_id: 10, assembly_id: 1, required: false},
#   {item_id: 11, assembly_id: 1, required: false},
#   {item_id: 132, assembly_id: 1, required: true},
#   {item_id: 134, assembly_id: 1, required: true},
#   {item_id: 12, assembly_id: 12, required: true},
#   {item_id: 134, assembly_id: 12, required: true},
#   {item_id: 13, assembly_id: 13, required: true},
#   {item_id: 134, assembly_id: 13, required: true},
#   {item_id: 15, assembly_id: 14, required: true},
#   {item_id: 134, assembly_id: 14, required: true},
#   {item_id: 17, assembly_id: 15, required: true},
#   {item_id: 134, assembly_id: 15, required: true},
#   {item_id: 18, assembly_id: 16, required: true},
#   {item_id: 19, assembly_id: 16, required: true},
#   {item_id: 20, assembly_id: 16, required: true},
#   {item_id: 21, assembly_id: 17, required: true},
#   {item_id: 22, assembly_id: 18, required: true},
#   {item_id: 23, assembly_id: 18, required: true},
#   {item_id: 24, assembly_id: 18, required: true},
#   {item_id: 25, assembly_id: 18, required: false},
#   {item_id: 134, assembly_id: 18, required: true},
#   {item_id: 26, assembly_id: 19, required: true},
#   {item_id: 27, assembly_id: 19, required: false},
#   {item_id: 28, assembly_id: 20, required: true},
#   {item_id: 134, assembly_id: 20, required: true},
#   {item_id: 29, assembly_id: 21, required: true},
#   {item_id: 30, assembly_id: 21, required: false},
#   {item_id: 33, assembly_id: 21, required: false},
#   {item_id: 34, assembly_id: 21, required: false},
#   {item_id: 35, assembly_id: 21, required: false},
#   {item_id: 134, assembly_id: 21, required: true},
#   {item_id: 31, assembly_id: 22, required: true},
#   {item_id: 32, assembly_id: 22, required: true},
#   {item_id: 134, assembly_id: 22, required: true},
#   {item_id: 36, assembly_id: 24, required: true},
#   {item_id: 37, assembly_id: 24, required: true},
#   {item_id: 38, assembly_id: 24, required: true},
#   {item_id: 39, assembly_id: 24, required: true},
#   {item_id: 40, assembly_id: 24, required: true},
#   {item_id: 41, assembly_id: 24, required: false},
#   {item_id: 42, assembly_id: 24, required: true},
#   {item_id: 43, assembly_id: 24, required: true},
#   {item_id: 44, assembly_id: 24, required: false},
#   {item_id: 134, assembly_id: 24, required: true},
#   {item_id: 46, assembly_id: 25, required: true},
#   {item_id: 134, assembly_id: 25, required: true},
#   {item_id: 47, assembly_id: 26, required: true},
#   {item_id: 48, assembly_id: 26, required: true},
#   {item_id: 49, assembly_id: 26, required: true},
#   {item_id: 50, assembly_id: 26, required: true},
#   {item_id: 51, assembly_id: 26, required: true},
#   {item_id: 134, assembly_id: 26, required: true},
#   {item_id: 52, assembly_id: 27, required: true},
#   {item_id: 53, assembly_id: 27, required: true},
#   {item_id: 64, assembly_id: 27, required: true},
#   {item_id: 134, assembly_id: 27, required: true},
#   {item_id: 54, assembly_id: 29, required: true},
#   {item_id: 55, assembly_id: 30, required: true},
#   {item_id: 56, assembly_id: 30, required: false},
#   {item_id: 57, assembly_id: 30, required: true},
#   {item_id: 58, assembly_id: 30, required: true},
#   {item_id: 59, assembly_id: 30, required: true},
#   {item_id: 60, assembly_id: 30, required: true},
#   {item_id: 61, assembly_id: 30, required: true},
#   {item_id: 62, assembly_id: 30, required: true},
#   {item_id: 63, assembly_id: 30, required: true},
#   {item_id: 64, assembly_id: 30, required: true},
#   {item_id: 134, assembly_id: 30, required: true},
#   {item_id: 79, assembly_id: 31, required: false},
#   {item_id: 80, assembly_id: 31, required: false},
#   {item_id: 81, assembly_id: 31, required: false},
#   {item_id: 82, assembly_id: 31, required: false},
#   {item_id: 83, assembly_id: 31, required: false},
#   {item_id: 84, assembly_id: 31, required: false},
#   {item_id: 85, assembly_id: 31, required: false},
#   {item_id: 86, assembly_id: 31, required: false},
#   {item_id: 87, assembly_id: 31, required: false},
#   {item_id: 88, assembly_id: 31, required: false},
#   {item_id: 89, assembly_id: 31, required: false},
#   {item_id: 90, assembly_id: 31, required: false},
#   {item_id: 91, assembly_id: 31, required: false},
#   {item_id: 98, assembly_id: 32, required: true},
#   {item_id: 99, assembly_id: 32, required: true},
#   {item_id: 100, assembly_id: 32, required: true},
#   {item_id: 101, assembly_id: 33, required: true},
#   {item_id: 102, assembly_id: 34, required: true},
#   {item_id: 104, assembly_id: 34, required: true},
#   {item_id: 105, assembly_id: 34, required: false},
#   {item_id: 106, assembly_id: 34, required: false},
#   {item_id: 107, assembly_id: 34, required: false},
#   {item_id: 108, assembly_id: 34, required: false},
#   {item_id: 109, assembly_id: 34, required: false},
#   {item_id: 110, assembly_id: 34, required: false},
#   {item_id: 111, assembly_id: 34, required: false},
#   {item_id: 112, assembly_id: 34, required: false},
#   {item_id: 113, assembly_id: 34, required: false},
#   {item_id: 114, assembly_id: 34, required: false},
#   {item_id: 115, assembly_id: 34, required: false},
#   {item_id: 116, assembly_id: 34, required: false},
#   {item_id: 117, assembly_id: 34, required: false},
#   {item_id: 118, assembly_id: 34, required: false},
#   {item_id: 119, assembly_id: 34, required: false},
#   {item_id: 120, assembly_id: 34, required: false},
#   {item_id: 121, assembly_id: 34, required: false},
#   {item_id: 122, assembly_id: 34, required: false},
#   {item_id: 123, assembly_id: 34, required: false},
#   {item_id: 124, assembly_id: 34, required: false},
#   {item_id: 103, assembly_id: 35, required: true},
#   {item_id: 104, assembly_id: 35, required: true},
#   {item_id: 105, assembly_id: 35, required: false},
#   {item_id: 106, assembly_id: 35, required: false},
#   {item_id: 107, assembly_id: 35, required: false},
#   {item_id: 108, assembly_id: 35, required: false},
#   {item_id: 109, assembly_id: 35, required: false},
#   {item_id: 110, assembly_id: 35, required: false},
#   {item_id: 111, assembly_id: 35, required: false},
#   {item_id: 112, assembly_id: 35, required: false},
#   {item_id: 113, assembly_id: 35, required: false},
#   {item_id: 114, assembly_id: 35, required: false},
#   {item_id: 115, assembly_id: 35, required: false},
#   {item_id: 116, assembly_id: 35, required: false},
#   {item_id: 117, assembly_id: 35, required: false},
#   {item_id: 118, assembly_id: 35, required: false},
#   {item_id: 119, assembly_id: 35, required: false},
#   {item_id: 120, assembly_id: 35, required: false},
#   {item_id: 121, assembly_id: 35, required: false},
#   {item_id: 122, assembly_id: 35, required: false},
#   {item_id: 123, assembly_id: 35, required: false},
#   {item_id: 124, assembly_id: 35, required: false},
#   {item_id: 125, assembly_id: 36, required: true},
#   {item_id: 126, assembly_id: 36, required: true},
#   {item_id: 127, assembly_id: 36, required: false},
#   {item_id: 128, assembly_id: 36, required: false},
#   {item_id: 129, assembly_id: 36, required: false},
#   {item_id: 130, assembly_id: 36, required: false},
#   {item_id: 136, assembly_id: 38, required: true},
#   {item_id: 138, assembly_id: 38, required: false},
#   {item_id: 137, assembly_id: 39, required: true},
#   {item_id: 138, assembly_id: 39, required: false},
#   {item_id: 132, assembly_id: 46, required: true},
#   {item_id: 134, assembly_id: 46, required: true},
#   {item_id: 92, assembly_id: 31, required: false},
#   {item_id: 93, assembly_id: 31, required: false},
#   {item_id: 94, assembly_id: 31, required: false},
#   {item_id: 95, assembly_id: 31, required: false},
#   {item_id: 96, assembly_id: 31, required: false},
#   {item_id: 97, assembly_id: 31, required: false},
#   {item_id: 134, assembly_id: 31, required: false}
# ])

# Assembly.create!([
#   {name: "BASIC NETWORK SERVICE - BNS08", assembly_number: "7640018098", assembly_type: nil},
#   {name: "BASIC PROFESSIONAL SERVICES - LEVEL 5", assembly_number: "7640012601", assembly_type: nil},
#   {name: "EXPERT COLOR PRODUCTION TRAINING", assembly_number: "7640020218", assembly_type: nil},
#   {name: "PROFESSIONAL SERVICES PROJECT FEE", assembly_number: "7640015255", assembly_type: nil},
#   {name: "LEASE RETURN 1ST UNIT", assembly_number: "7640018268", assembly_type: nil},
#   {name: "LEASE RETURN ADD'L UNITS", assembly_number: "7640018269", assembly_type: nil},
#   {name: "KMPF LEASE RETURN 1ST UNIT", assembly_number: "7640020486", assembly_type: nil},
#   {name: "KMPF LEASE RETURN ADDL UNITS", assembly_number: "7640020488", assembly_type: nil},
#   {name: "ADDITIONAL DELIVERY CHARGE", assembly_number: "7640018271", assembly_type: nil},
#   {name: "SMART-UPS 1500VA LCD 120V WITH SMARTCONN", assembly_number: "2CL133", assembly_type: nil},
#   {name: "C14000 C12000 FREIGHT", assembly_number: "7640021366", assembly_type: "main unit"},
#   {name: "PF-712 PAPER FEED", assembly_number: "AC4GWY1", assembly_type: "paper handling"},
#   {name: "PF-713 PAPER FEED WITH SCANNER", assembly_number: "AC4HWY1", assembly_type: "paper handling"},
#   {name: "PF-812 LONG SHEET 3 DRAWER PAPER FEED", assembly_number: "AC4JWY1", assembly_type: "paper handling"},
#   {name: "FA-505 PF CONNECTION KIT", assembly_number: "AC4MWY1", assembly_type: "paper handling"},
#   {name: "MB-511 BYPASS BANNER TRAY", assembly_number: "AC4KWY1", assembly_type: "paper handling"},
#   {name: "IM-101 INTELLIGENT MEDIA SENSOR", assembly_number: "ACCXWY1", assembly_type: "finishing"},
#   {name: "IQ-501 INTELLIGENT QUALITY OPTIMIZER", assembly_number: "A8FRWY1", assembly_type: "finishing"},
#   {name: "RU-518M RELAY UNIT", assembly_number: "A9CEWY2", assembly_type: "finishing"},
#   {name: "LS-507 LARGE STACKER", assembly_number: "AAPKWY1", assembly_type: "finishing"},
#   {name: "LC-502 STACKER CART", assembly_number: "ACHKWY1", assembly_type: "finishing"},
#   {name: "TU-510 TRIMMER UNIT", assembly_number: "AC3TWY1", assembly_type: "finishing"},
#   {name: "SD-506 SADDLE STITCH UNIT", assembly_number: "A0H2WY3", assembly_type: "finishing"},
#   {name: "SD-513 SADDLE STITCHER", assembly_number: "A65UWY2", assembly_type: "finishing"},
#   {name: "PB-503  PERFECT BINDER", assembly_number: "A15XW13", assembly_type: "finishing"},
#   {name: "RU-510 RELAY UNIT", assembly_number: "A4FCWY2", assembly_type: "finishing"},
#   {name: "WT-518 WORK TABLE", assembly_number: "ACT2WY1", assembly_type: "main unit"},
#   {name: "PLOCKMATIC SD-350 BOOKLETMAKER", assembly_number: "10207010", assembly_type: "finishing"},
#   {name: "GBC PUNCH G2", assembly_number: "7718800", assembly_type: "finishing"},
#   {name: "EF-106 ENVELOPE FUSER", assembly_number: "ACT1W21", assembly_type: "paper handling"},
#   {name: "IC-610 KM IMAGE CONTROLLER", assembly_number: "ACMD0Y1", assembly_type: "controller"},
#   {name: "IC-318 FIERY IMAGE CONTROLLER", assembly_number: "ACAYWY1", assembly_type: "controller"},
#   {name: "IC-319 FIERY PREMIUM IMAGE CONTROLLER", assembly_number: "ACVAWY1", assembly_type: "controller"},
#   {name: "IC-316 CREO CONTROLLER", assembly_number: "ACN1WY1", assembly_type: "controller"},
#   {name: "ACCURIOPRESS C12000", assembly_number: nil, assembly_type: "engine"},
#   {name: "OT-512 OUTPUT TRAY", assembly_number: "AC8WWY1", assembly_type: "paper output"},
#   {name: "DELIVERY & INSTALL", assembly_number: nil, assembly_type: "main unit"},
#   {name: "LEASE RETURNS", assembly_number: nil, assembly_type: "main unit"},
#   {name: "C12000/C14000 FUSER LOADING CART", assembly_number: nil, assembly_type: "main unit"},
#   {name: "ACCURIOPRESS C12000", assembly_number: "AC0D011", assembly_type: "engine"},
#   {name: "ORU PARTS KIT C12000 & C14000 - LITE", assembly_number: "7640021368", assembly_type: "main unit"},
#   {name: "ORU PARTS KIT C12000 AND C14000 - ADVANCED", assembly_number: "7640021367", assembly_type: "main unit"},
#   {name: "ADDTIONAL PROFESSIONAL SERVICES", assembly_number: nil, assembly_type: "main unit"},
#   {name: "FS-541 STAPLE FINISHER", assembly_number: "AAUUWY1", assembly_type: "paper output"}
# ])

# Item.create!([
#   {item_number: "AC0D011", description: "ACCURIOPRESS C12000", branch_floor_price: "90835.37", target_price: "99220.17", part_type: "engine"},
#   {item_number: "7640021366", description: "C14000 C12000 FREIGHT (TO BE QUOTED)", branch_floor_price: "1.0", target_price: "1.0", part_type: "delivery/install"},
#   {item_number: "7640018098", description: "BASIC NETWORK SERVICE - BNS08", branch_floor_price: "1380.0", target_price: "1380.0", part_type: "delivery/install"},
#   {item_number: "7640012601", description: "BASIC PROFESSIONAL SERVICES - LEVEL 5", branch_floor_price: "3000.0", target_price: "3000.0", part_type: "delivery/install"},
#   {item_number: "7640020218", description: "EXPERT COLOR PRODUCTION TRAINING", branch_floor_price: "5000.0", target_price: "5000.0", part_type: "delivery/install"},
#   {item_number: "7640015255", description: "PROFESSIONAL SERVICES PROJECT FEE", branch_floor_price: "1.0", target_price: "1.0", part_type: "delivery/install"},
#   {item_number: "7640018268", description: "LEASE RETURN 1ST UNIT", branch_floor_price: "400.0", target_price: "400.0", part_type: "delivery/install"},
#   {item_number: "7640018269", description: "LEASE RETURN ADD'L UNITS", branch_floor_price: "300.0", target_price: "300.0", part_type: "delivery/install"},
#   {item_number: "7640020486", description: "KMPF LEASE RETURN 1ST UNIT", branch_floor_price: "400.0", target_price: "400.0", part_type: "delivery/install"},
#   {item_number: "7640020488", description: "KMPF LEASE RETURN ADDL UNITS", branch_floor_price: "300.0", target_price: "300.0", part_type: "delivery/install"},
#   {item_number: "7640018271", description: "ADDITIONAL DELIVERY CHARGE", branch_floor_price: "50.0", target_price: "50.0", part_type: "delivery/install"},
#   {item_number: "AC4GWY1", description: "PF-712 PAPER FEED", branch_floor_price: "7646.64", target_price: "8823.05", part_type: "paper handling"},
#   {item_number: "AC4HWY1", description: "PF-713 PAPER FEED WITH SCANNER", branch_floor_price: "11901.07", target_price: "13732.0", part_type: "paper handling"},
#   {item_number: "ACMHWY1", description: "UK-112 HDD", branch_floor_price: "1600.0", target_price: "1846.15", part_type: "paper handling"},
#   {item_number: "AC4JWY1", description: "PF-812 LONG SHEET 3 DRAWER PAPER FEED", branch_floor_price: "14400.0", target_price: "16616.0", part_type: "paper handling"},
#   {item_number: "A1RKWY3", description: "HT-506 HEATER FOR PF-710", branch_floor_price: "1368.11", target_price: "1578.59", part_type: "paper handling"},
#   {item_number: "AC4MWY1", description: "FA-505 PF CONNECTION KIT", branch_floor_price: "912.33", target_price: "1052.69", part_type: "paper handling"},
#   {item_number: "AC4KWY1", description: "MB-511 BYPASS BANNER TRAY", branch_floor_price: "3194.67", target_price: "3686.15", part_type: "paper handling"},
#   {item_number: "ACR3WY1", description: "MK-760 BANNER INPUT KIT", branch_floor_price: "357.33", target_price: "412.31", part_type: "paper handling"},
#   {item_number: "ACR4WY1", description: "MK-761 BANNER OUTPUT KIT", branch_floor_price: "565.33", target_price: "652.31", part_type: "paper handling"},
#   {item_number: "ACCXWY1", description: "IM-101 INTELLIGENT MEDIA SENSOR", branch_floor_price: "774.0", target_price: "893.0", part_type: "finishing"},
#   {item_number: "A8FRWY1", description: "IQ-501 INTELLIGENT QUALITY OPTIMIZER", branch_floor_price: "10870.0", target_price: "12184.62", part_type: "finishing"},
#   {item_number: "ACMAWY1", description: "VI-514 VIDEO INTERFACE FOR IQ-501", branch_floor_price: "1841.91", target_price: "2125.28", part_type: "finishing"},
#   {item_number: "AC5RWY1", description: "RU-702 PURGE TRAY", branch_floor_price: "3046.0", target_price: "3352.0", part_type: "finishing"},
#   {item_number: "AC5KWY1", description: "UK-301 AUTO INSPECTION UNIT", branch_floor_price: "4949.0", target_price: "5446.0", part_type: "finishing"},
#   {item_number: "A9CEWY2", description: "RU-518M RELAY UNIT", branch_floor_price: "5226.67", target_price: "6030.77", part_type: "finishing"},
#   {item_number: "A9CFWY1", description: "HM-103 HUMIDIFICATION UNIT FOR RU-518", branch_floor_price: "6402.0", target_price: "7175.39", part_type: "finishing"},
#   {item_number: "AC8WWY1", description: "OT-512 OUTPUT TRAY", branch_floor_price: "2514.13", target_price: "2900.92", part_type: "finishing"},
#   {item_number: "AAUUWY1", description: "FS-541 STAPLE FINISHER", branch_floor_price: "4316.32", target_price: "4980.37", part_type: "finishing"},
#   {item_number: "AC8UW11", description: "PK-525 PUNCH KIT", branch_floor_price: "479.4", target_price: "553.15", part_type: "finishing"},
#   {item_number: "AAPKWY1", description: "LS-507 LARGE STACKER", branch_floor_price: "11722.67", target_price: "13526.15", part_type: "finishing"},
#   {item_number: "ACHKWY1", description: "LC-502 STACKER CART", branch_floor_price: "663.36", target_price: "765.42", part_type: "finishing"},
#   {item_number: "A04HWY2", description: "PI-502 POST INSERTER FOR FS-532", branch_floor_price: "663.0", target_price: "741.82", part_type: "finishing"},
#   {item_number: "A4F5WY1", description: "MK-732 MOUNT KIT FOR PI-506", branch_floor_price: "257.0", target_price: "286.77", part_type: "finishing"},
#   {item_number: "A4F4WY1", description: "SD-510 SADDLE STITCH UNIT", branch_floor_price: "1568.0", target_price: "1704.0", part_type: "finishing"},
#   {item_number: "AC3TWY1", description: "TU-510 TRIMMER UNIT", branch_floor_price: "18666.67", target_price: "21538.46", part_type: "finishing"},
#   {item_number: "ACJ6WY1", description: "TU-504 SLITTER FOR TU-510", branch_floor_price: "3221.33", target_price: "3716.92", part_type: "finishing"},
#   {item_number: "ACJ5WY1", description: "CR-102 CREASER FOR TU-510", branch_floor_price: "2186.67", target_price: "2523.08", part_type: "finishing"},
#   {item_number: "ACWKWY1", description: "CR-103 CONVEX CREASING UNIT FOR TU-510", branch_floor_price: "1814.0", target_price: "2093.0", part_type: "finishing"},
#   {item_number: "ACWNWY1", description: "PE-101 FEED DIRECTION PERF FOR TU-510", branch_floor_price: "3627.0", target_price: "4185.0", part_type: "finishing"},
#   {item_number: "ACWPWY1", description: "PE-102 CROSS DIRECTION PERF TU-510", branch_floor_price: "2539.0", target_price: "2930.0", part_type: "finishing"},
#   {item_number: "ACWMWY1", description: "MK-765 DUST BOX FOR TU-510", branch_floor_price: "2187.0", target_price: "2524.0", part_type: "finishing"},
#   {item_number: "ACJ7WY1", description: "MK-764 BANNER OUTPUT FOR TU-510", branch_floor_price: "2720.0", target_price: "3138.46", part_type: "finishing"},
#   {item_number: "ACJ8WY1", description: "JS-507 BUSINESS CARD TRAY FOR TU-510", branch_floor_price: "725.33", target_price: "836.92", part_type: "finishing"},
#   {item_number: "A0H0W12", description: "FD-503 MULTI FOLDING UNIT", branch_floor_price: "7210.67", target_price: "8320.0", part_type: "finishing"},
#   {item_number: "A0H2WY3", description: "SD-506 SADDLE STITCH UNIT", branch_floor_price: "15789.0", target_price: "17699.07", part_type: "finishing"},
#   {item_number: "A65UWY2", description: "SD-513 SADDLE STITCHER", branch_floor_price: "9201.0", target_price: "10313.85", part_type: "finishing"},
#   {item_number: "A729WY1", description: "SD-513/F SADDLE STITCH UNIT - FRONT", branch_floor_price: "9188.0", target_price: "10298.77", part_type: "finishing"},
#   {item_number: "A65XWY1", description: "CR-101 CREASER UNIT FOR SD-513", branch_floor_price: "5842.0", target_price: "6547.7", part_type: "finishing"},
#   {item_number: "A65VWY1", description: "FD-504 SQUARE FOLD MODULE FOR SD-513", branch_floor_price: "7066.0", target_price: "7920.0", part_type: "finishing"},
#   {item_number: "A65WWY1", description: "TU-503 TRIMMER UNIT FOR SD-513", branch_floor_price: "9592.0", target_price: "10752.0", part_type: "finishing"},
#   {item_number: "A15XW13", description: "PB-503  PERFECT BINDER", branch_floor_price: "26279.0", target_price: "29458.22", part_type: "finishing"},
#   {item_number: "A4FCWY2", description: "RU-510 RELAY UNIT", branch_floor_price: "2046.0", target_price: "2292.31", part_type: "finishing"},
#   {item_number: "ACT2WY1", description: "WT-518 WORK TABLE", branch_floor_price: "597.33", target_price: "689.23", part_type: "finishing"},
#   {item_number: "10207010", description: "PLOCKMATIC SD-350 BOOKLETMAKER", branch_floor_price: "12569.36", target_price: "14503.11", part_type: "finishing"},
#   {item_number: "10200011", description: "PLOCKMATIC 50 SHEET UPGRADE KIT", branch_floor_price: "9333.0", target_price: "10461.54", part_type: "finishing"},
#   {item_number: "10307000", description: "PLOCKMATIC FACE TRIMMER", branch_floor_price: "7796.0", target_price: "8738.47", part_type: "finishing"},
#   {item_number: "10507000", description: "PLOCKMATIC BOOKFOLD", branch_floor_price: "7467.0", target_price: "8369.24", part_type: "finishing"},
#   {item_number: "10407000", description: "PLOCKMATIC COVER FEEDER", branch_floor_price: "2800.0", target_price: "3138.47", part_type: "finishing"},
#   {item_number: "12207000", description: "PLOCKMATIC RCT (INCL INTERFACE MODULE)", branch_floor_price: "23605.0", target_price: "26461.54", part_type: "finishing"},
#   {item_number: "4707000", description: "PLOCKMATIC HIGH CAPACITY BELT STACKER", branch_floor_price: "4455.83", target_price: "5141.34", part_type: "finishing"},
#   {item_number: "12200018", description: "PLOCKMATIC TRIM WASTE CONVEYER FOR RCT", branch_floor_price: "3485.16", target_price: "4021.34", part_type: "finishing"},
#   {item_number: "7640020192", description: "PLOCKMATIC INSTALL & TRAINING - KM", branch_floor_price: "900.0", target_price: "900.0", part_type: "finishing"},
#   {item_number: "A6H9WY2", description: "MK-737 MOUNT KIT FOR 3RD PARTY OPTIONS", branch_floor_price: "881.0", target_price: "985.85", part_type: "finishing"},
#   {item_number: "7718800", description: "GBC PUNCH G2", branch_floor_price: "8831.45", target_price: "10190.14", part_type: "finishing"},
#   {item_number: "7714901", description: "DIE  COIL  RND 44/47H", branch_floor_price: "658.59", target_price: "759.91", part_type: "finishing"},
#   {item_number: "7714902", description: "DIE  WIRE 2:1  RND 21/23H", branch_floor_price: "658.59", target_price: "759.91", part_type: "finishing"},
#   {item_number: "7714903", description: "DIE  WIRE 3:1  RND 32/34H", branch_floor_price: "658.59", target_price: "759.91", part_type: "finishing"},
#   {item_number: "7714904", description: "DIE 3 HOLE 8MM", branch_floor_price: "626.84", target_price: "723.28", part_type: "finishing"},
#   {item_number: "7714905", description: "DIE 3/5/7 HOLE 8MM", branch_floor_price: "626.84", target_price: "723.28", part_type: "finishing"},
#   {item_number: "7714909", description: "DIE VELOBIND 11 HOLE LTR", branch_floor_price: "658.59", target_price: "759.91", part_type: "finishing"},
#   {item_number: "7714911", description: "DIE  COMBBIND 19/21H", branch_floor_price: "574.48", target_price: "662.86", part_type: "finishing"},
#   {item_number: "7714912", description: "DIE  WIRE 2:1  SQ  21/23H", branch_floor_price: "626.84", target_price: "723.28", part_type: "finishing"},
#   {item_number: "7714913", description: "DIE  WIRE 3:1  SQ 32/34H", branch_floor_price: "626.84", target_price: "723.28", part_type: "finishing"},
#   {item_number: "7714914", description: "DIE  COIL  OVAL  44/47H", branch_floor_price: "1460.0", target_price: "1684.62", part_type: "finishing"},
#   {item_number: "7714906", description: "DIE 2/4 HOLE 8MM", branch_floor_price: "626.84", target_price: "723.28", part_type: "finishing"},
#   {item_number: "7714917", description: "DIE  COIL RND 44/47H HD", branch_floor_price: "1872.63", target_price: "2160.72", part_type: "finishing"},
#   {item_number: "7714918", description: "DIE 3 HOLE 8MM HD", branch_floor_price: "1083.89", target_price: "1250.65", part_type: "finishing"},
#   {item_number: "7714919", description: "DIE COMBBIND 19/21H HD", branch_floor_price: "2083.69", target_price: "2404.26", part_type: "finishing"},
#   {item_number: "7723000", description: "GBC WIRE BINDER G1", branch_floor_price: "30049.0", target_price: "33685.34", part_type: "finishing"},
#   {item_number: "7714915", description: "DIE EWIRE RND", branch_floor_price: "666.52", target_price: "769.06", part_type: "finishing"},
#   {item_number: "7714916", description: "DIE EWIRE SQ", branch_floor_price: "666.52", target_price: "769.06", part_type: "finishing"},
#   {item_number: "7717962", description: "EWIRE SPOOL ELEMENT SIZE 'A' BLACK", branch_floor_price: "121.0", target_price: "126.0", part_type: "finishing"},
#   {item_number: "7717963", description: "EWIRE SPOOL ELEMENT SIZE 'B'  BLACK", branch_floor_price: "105.0", target_price: "110.0", part_type: "finishing"},
#   {item_number: "7717964", description: "EWIRE SPOOL ELEMENT SIZE 'C'  BLACK", branch_floor_price: "98.0", target_price: "102.0", part_type: "finishing"},
#   {item_number: "7717965", description: "EWIRE SPOOL ELEMENT SIZE 'D'  BLACK", branch_floor_price: "96.0", target_price: "100.0", part_type: "finishing"},
#   {item_number: "7717966", description: "EWIRE SPOOL ELEMENT SIZE 'E'  BLACK", branch_floor_price: "87.0", target_price: "91.0", part_type: "finishing"},
#   {item_number: "7717968", description: "EWIRE SPOOL ELEMENT SIZE 'A'  WHITE", branch_floor_price: "122.0", target_price: "127.0", part_type: "finishing"},
#   {item_number: "7717969", description: "EWIRE SPOOL ELEMENT SIZE 'B'  WHITE", branch_floor_price: "106.0", target_price: "111.0", part_type: "finishing"},
#   {item_number: "7717970", description: "EWIRE SPOOL ELEMENT SIZE 'C'  WHITE", branch_floor_price: "99.0", target_price: "103.0", part_type: "finishing"},
#   {item_number: "7717971", description: "EWIRE SPOOL ELEMENT SIZE 'D'  WHITE", branch_floor_price: "97.0", target_price: "101.0", part_type: "finishing"},
#   {item_number: "7717972", description: "EWIRE SPOOL ELEMENT SIZE 'E'  WHITE", branch_floor_price: "88.0", target_price: "92.0", part_type: "finishing"},
#   {item_number: "7717974", description: "EWIRE SPOOL ELEMENT SIZE 'A'  SILVER", branch_floor_price: "132.0", target_price: "138.0", part_type: "finishing"},
#   {item_number: "7717975", description: "EWIRE SPOOL ELEMENT SIZE 'B'  SILVER", branch_floor_price: "115.0", target_price: "120.0", part_type: "finishing"},
#   {item_number: "7717976", description: "EWIRE SPOOL ELEMENT SIZE 'C'  SILVER", branch_floor_price: "106.0", target_price: "111.0", part_type: "finishing"},
#   {item_number: "7717977", description: "EWIRE SPOOL ELEMENT SIZE 'D'  SILVER", branch_floor_price: "104.0", target_price: "109.0", part_type: "finishing"},
#   {item_number: "7717978", description: "EWIRE SPOOL ELEMENT SIZE 'E'  SILVER", branch_floor_price: "96.0", target_price: "100.0", part_type: "finishing"},
#   {item_number: "ACT1W21", description: "EF-106 ENVELOPE FUSER", branch_floor_price: "5653.33", target_price: "6523.08", part_type: "finishing"},
#   {item_number: "A5AWRX0011A", description: "FUSER LOADING WAGON", branch_floor_price: "1062.45", target_price: "1225.91", part_type: "finishing"},
#   {item_number: "ACY9W21", description: "CU-104 CLEANING UNIT FOR EF-106", branch_floor_price: "363.0", target_price: "419.0", part_type: "finishing"},
#   {item_number: "ACMD0Y1", description: "IC-610 KM IMAGE CONTROLLER", branch_floor_price: "8503.44", target_price: "9811.66", part_type: "print controller"},
#   {item_number: "ACAYWY1", description: "IC-318 FIERY IMAGE CONTROLLER", branch_floor_price: "23893.33", target_price: "27569.23", part_type: "print controller"},
#   {item_number: "ACVAWY1", description: "IC-319 FIERY PREMIUM IMAGE CONTROLLER", branch_floor_price: "41130.67", target_price: "47458.46", part_type: "print controller"},
#   {item_number: "ACMKWY1", description: "VI-515 VIDEO INTERFACE FOR CONTROLLER", branch_floor_price: "373.33", target_price: "430.77", part_type: "print controller"},
#   {item_number: "45206712", description: "FIERY IMPOSE WITHOUT ACRBT-PTSTP", branch_floor_price: "1779.0", target_price: "2053.0", part_type: "print controller"},
#   {item_number: "45206716", description: "FIERY COMPOSE WITHOUT ACRBT-PTSTP", branch_floor_price: "816.0", target_price: "942.0", part_type: "print controller"},
#   {item_number: "45112781", description: "FIERY JOBFLOW W / MAINT", branch_floor_price: "4364.0", target_price: "4776.0", part_type: "print controller"},
#   {item_number: "100000000000.0", description: "FIERY JOBFLOW ANNUAL MAINTENANCE", branch_floor_price: "865.19", target_price: "899.0", part_type: "print controller"},
#   {item_number: "45206722", description: "FIERY JOBMASTER WITHOUT ACRBT-PTSTP", branch_floor_price: "3267.0", target_price: "3770.0", part_type: "print controller"},
#   {item_number: "45206725", description: "FIERY JOBMASTER-IMPOSE W-OUT ACRBT-PTSTP", branch_floor_price: "4667.0", target_price: "5385.0", part_type: "print controller"},
#   {item_number: "100000000000.0", description: "FIERY JOBMASTER ANNUAL MAINTENANCE", branch_floor_price: "674.08", target_price: "700.0", part_type: "print controller"},
#   {item_number: "100000000000.0", description: "FIERY JOBMASTER-IMPOSE ANNUAL MAINT", branch_floor_price: "886.0", target_price: "1000.0", part_type: "print controller"},
#   {item_number: "45206625", description: "ADOBE ACROBAT 2017 AND PITSTOP EDIT 2019", branch_floor_price: "327.0", target_price: "377.0", part_type: "print controller"},
#   {item_number: "45201479", description: "FIERY GRAPHIC ARTS PRO - 1YR LICENSE KIT", branch_floor_price: "1348.15", target_price: "1555.55", part_type: "print controller"},
#   {item_number: "45201481", description: "FIERY GRAPHIC ARTS PRO - 2YR LICENSE KIT", branch_floor_price: "2555.56", target_price: "2948.72", part_type: "print controller"},
#   {item_number: "45201483", description: "FIERY GRAPHIC ARTS PRO - 3YR LICENSE KIT", branch_floor_price: "3629.63", target_price: "4188.03", part_type: "print controller"},
#   {item_number: "45201485", description: "FIERY GRAPHIC ARTS PRO - 4YR LICENSE KIT", branch_floor_price: "4296.29", target_price: "4957.26", part_type: "print controller"},
#   {item_number: "45201487", description: "FIERY GRAPHIC ARTS PRO - 5YR LICENSE KIT", branch_floor_price: "5037.04", target_price: "5811.97", part_type: "print controller"},
#   {item_number: "45162875", description: "22IN FACI/FURNITURE BUNDLE FOR IC-313 NX", branch_floor_price: "2403.0", target_price: "2588.0", part_type: "print controller"},
#   {item_number: "45150368", description: "FURNITURE FOR FIERY NX STATION LS W 27IN", branch_floor_price: "3953.0", target_price: "4430.77", part_type: "print controller"},
#   {item_number: "45204332", description: "EFI BUNDLE NX-22IN STAND+CPS SW+JM-IM+GA", branch_floor_price: "10000.0", target_price: "11538.46", part_type: "print controller"},
#   {item_number: "45204557", description: "EFI BUNDLE CPS SW ONLY+JM-IM+GA PRO", branch_floor_price: "8881.48", target_price: "10247.86", part_type: "print controller"},
#   {item_number: "45189980", description: "3-BAY CASE NX PREM GEN III EXT HDD KIT", branch_floor_price: "3514.0", target_price: "3938.47", part_type: "print controller"},
#   {item_number: "45162419", description: "NX PRM HD 500GB+(X2)2TB HDD CARRIERS", branch_floor_price: "3372.0", target_price: "3778.47", part_type: "print controller"},
#   {item_number: "ACN1WY1", description: "IC-316 CREO CONTROLLER", branch_floor_price: "17770.67", target_price: "20504.62", part_type: "print controller"},
#   {item_number: "ACYNWY1", description: "UK-117 UPGRADE KIT REQ FOR CREO IC-316", branch_floor_price: "6709.33", target_price: "7741.54", part_type: "print controller"},
#   {item_number: "63900289A", description: "IC-316 FAST PACK", branch_floor_price: "3703.71", target_price: "4273.51", part_type: "print controller"},
#   {item_number: "63900290A", description: "IC-316 ACTION PACK", branch_floor_price: "3703.71", target_price: "4273.51", part_type: "print controller"},
#   {item_number: "63900291A", description: "IC-316 MATCH PACK", branch_floor_price: "3703.71", target_price: "4273.51", part_type: "print controller"},
#   {item_number: "63900292A", description: "IC-316 TRANS PACK", branch_floor_price: "7037.04", target_price: "8119.66", part_type: "print controller"},
#   {item_number: "R5427011136466GEN2", description: "AU-205HGEN2  SQ-2020-94643", branch_floor_price: "190.77", target_price: "260.31", part_type: "power supply"},
#   {item_number: "EV20830L630GNS", description: "ESP POWER FILTER 240V/30A", branch_floor_price: "1115.0", target_price: "1115.0", part_type: "power supply"},
#   {item_number: "EVS20830L630GNS", description: "ESP ENVISIONSENSE PMS 208V-240V/30A", branch_floor_price: "1375.0", target_price: "1375.0", part_type: "power supply"},
#   {item_number: "XGPCS15DKM", description: "ESP DIAGNOSTIC POWER FILTER 120V/15A", branch_floor_price: "222.5", target_price: "248.75", part_type: "power supply"},
#   {item_number: "2CL133", description: "SMART-UPS 1500VA LCD 120V WITH SMARTCONN", branch_floor_price: "696.06", target_price: "773.0", part_type: "misc"},
#   {item_number: "7640021368", description: "ORU LITE PARTS KIT C12000 C14000", branch_floor_price: "5398.97", target_price: "6229.58", part_type: "misc"},
#   {item_number: "7640021367", description: "ORU ADVANCED PARTS KIT C12000 C14000", branch_floor_price: "8511.03", target_price: "9820.42", part_type: "misc"},
#   {item_number: "7640018666", description: "1 DAY ON SITE ORU TRAINING PER PERSON", branch_floor_price: "650.0", target_price: "650.0", part_type: "misc"}
# ])

